version: '3.8'
services:
  python-predictor:
    container_name: python-predictor
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - zerowaste-api_app-network
    volumes:
      - app:/usr/src/app
      
networks:
  zerowaste-api_app-network:
    external: true

volumes:
    pred:
